'use strict';
const $ = id => document.getElementById(id);
const token = document.querySelector('meta[name="workbench-token"]').content;
let settings, state = {}, rows = [], resultTargets = [], offset = 0, resultTotal = 0, lastFinished = null, toastTimer, polling = false, resultBusy = false;
const numeric = ['attempts','timeout','workers','rate','max_bytes','source_timeout','top','min_success'];
const fmt = n => Number(n || 0).toLocaleString('ru-RU');
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message, error=false) { $('toast').textContent=message; $('toast').className=error?'error':''; $('toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').hidden=true,error?9000:4500); }
async function api(path, body) { const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'X-Workbench-Token':token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)}); const value=await response.json(); if(!response.ok)throw new Error(value.error||'Ошибка приложения'); return value; }
function showTab(name) { document.querySelectorAll('.page').forEach(n=>n.classList.toggle('active',n.id==='page-'+name)); document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.tab===name)); $('page-label').textContent={scan:'Проверка',results:'Результаты',sources:'Источники',help:'Как это работает'}[name]; if(name==='results')loadResults(); }
document.querySelectorAll('[data-tab]').forEach(n=>n.onclick=()=>showTab(n.dataset.tab));
document.querySelectorAll('[data-go]').forEach(n=>n.onclick=()=>showTab(n.dataset.go));
function addTarget(target={}) { if($('targets').children.length>=20){toast('Максимум 20 сервисов.',true);return;} const node=document.createElement('div');node.className='target';node.innerHTML=`<div class="target-head"><span>◎</span><input data-field="name" aria-label="Название сервиса" placeholder="Название сервиса" value="${esc(target.name||'Свой сервис')}"><button data-remove title="Удалить сервис" aria-label="Удалить сервис">×</button></div><label class="target-url">URL для проверки<input data-field="url" type="url" placeholder="https://example.org/health" value="${esc(target.url||'')}"></label><div class="field-grid"><label>Допустимые HTTP-коды<input data-field="statuses" placeholder="200, 204 или 200-299" value="${esc(target.statuses ? (target.statuses.length===100 && target.statuses[0]===200?'200-299':target.statuses.join(', ')):'200-299')}"></label><label>Текст в ответе (необязательно)<input data-field="contains" placeholder="Например: healthy" value="${esc(target.contains||'')}"></label></div><details class="advanced"><summary>Метод, заголовки и SHA-256</summary><label>Метод<select data-field="method"><option>GET</option><option>HEAD</option></select></label><label>Заголовки запроса — JSON<textarea data-field="headers" rows="2" spellcheck="false">${esc(JSON.stringify(target.headers||{}))}</textarea></label><label>SHA-256 тела ответа (необязательно)<input data-field="sha256" value="${esc(target.sha256||'')}" placeholder="Ожидаемый хеш ответа"></label></details>`;node.querySelector('[data-field="method"]').value=target.method||'GET';node.querySelector('[data-remove]').onclick=()=>{if($('targets').children.length===1){toast('Нужен хотя бы один сервис.',true);return;}node.remove();};$('targets').appendChild(node); }
function statuses(raw) { const values=new Set();for(const part of raw.split(',')){const m=part.trim().match(/^(\d{3})(?:\s*-\s*(\d{3}))?$/);if(!m)throw new Error('Укажите HTTP-коды: например 200, 204 или 200-299.');const a=Number(m[1]),b=Number(m[2]||m[1]);if(a<100||b>599||b<a)throw new Error('HTTP-код должен быть от 100 до 599.');for(let i=a;i<=b;i++)values.add(i);}return [...values]; }
function getSettings() { const copy={...settings};for(const key of numeric)copy[key]=Number($(key).value);copy.sort=$('sort').value;copy.use_sources=$('use_sources').checked;copy.sources=$('sources').value.split('\n').map(s=>s.trim()).filter(Boolean);copy.proxies=$('proxies').value;copy.targets=[...$('targets').children].map(node=>{const v=key=>node.querySelector(`[data-field="${key}"]`).value.trim();let headers;try{headers=JSON.parse(v('headers')||'{}');}catch{throw new Error('Заголовки сервиса должны быть корректным JSON.');}if(!v('url'))throw new Error('Введите URL каждого сервиса.');return {name:v('name'),url:v('url'),method:v('method'),statuses:statuses(v('statuses')),contains:v('contains')||null,sha256:v('sha256')||null,headers};});return copy; }
function fill(value) { settings=value;numeric.forEach(key=>{const el=$(key);if(el.tagName==='SELECT'&&![...el.options].some(o=>o.value===String(value[key]))){const option=new Option(`${Math.round(value[key]*100)}%`,value[key]);el.add(option);}el.value=value[key];});$('sort').value=value.sort;$('use_sources').checked=value.use_sources;$('sources').value=value.sources.join('\n');$('proxies').value=value.proxies;$('targets').replaceChildren();value.targets.forEach(addTarget);syncResultControls();updateSourceCount(); }
function syncResultControls(){ $('result-sort').value=$('sort').value;const val=$('min_success').value;if(![...$('result-min').options].some(o=>o.value===val))$('result-min').add(new Option(`${Math.round(Number(val)*100)}%`,val));$('result-min').value=val;$('result-top').value=$('top').value; }
function updateSourceCount(){ $('source-count').textContent=$('use_sources').checked?fmt(new Set($('sources').value.split('\n').map(s=>s.trim()).filter(Boolean)).size):'Выключены'; }
async function save(){try{settings=await api('/api/settings',getSettings());toast('Настройки сохранены.');updateSourceCount();}catch(e){toast(e.message,true);}}
async function start(action){try{let value=getSettings();if(action==='export'){value.sort=$('result-sort').value;value.min_success=Number($('result-min').value);value.top=Number($('result-top').value);$('sort').value=value.sort;$('min_success').value=value.min_success;$('top').value=value.top;}else{syncResultControls();}setBusy(true);await api('/api/start',{action,settings:value});settings=value;toast(action==='export'?'Формируем файлы по выбранным фильтрам.':'Запуск принят. Прогресс появится через несколько секунд.');if(action==='collect')showTab('sources');await poll();}catch(e){toast(e.message,true);setBusy(Boolean(state.running));}}
function setBusy(active){['start','resume','recheck','collect','export'].forEach(id=>$(id).disabled=active);$('stop').disabled=!active;}
const phases={starting:'Запуск',collecting:'Сбор источников',scanning:'Проверка',exporting:'Сохранение',complete:'Завершено',stopped:'Остановлено',interrupted:'Прервано',error:'Ошибка'};
function duration(seconds){if(seconds==null)return '—';if(seconds<60)return '< 1 мин';if(seconds<3600)return Math.ceil(seconds/60)+' мин';return (seconds/3600).toFixed(1)+' ч';}
function renderState(value){state=value;const p=value.progress||{},job=value.job||{};setBusy(value.running);$('phase').textContent=job.stopping&&value.running?'Останавливаем…':phases[p.phase]||'Готов к запуску';$('checked').textContent=fmt(p.checked);$('candidates').textContent=fmt(p.candidates);const percent=p.candidates?Math.min(100,100*(p.checked||0)/p.candidates):0;$('percent').textContent=percent.toFixed(1)+'%';$('progress-bar').style.width=percent+'%';$('speed').textContent=value.running&&p.phase==='scanning'?String(p.speed??'—'):'—';$('eta').textContent=value.running&&p.phase==='scanning'?duration(p.eta_seconds):'—';$('progress-text').textContent=p.phase==='collecting'?`Источников обработано: ${p.sources_done||0} / ${p.sources_total||0}`:p.candidates?`Осталось проверить: ${fmt(Math.max(0,p.candidates-(p.checked||0)))}`:'Все собранные адреса попадут в проверку';$('job-detail').textContent=job.id?`${{run:'Сбор + проверка',scan:'Продолжение базы',recheck:'Новая проверка',collect:'Сбор адресов',export:'Экспорт'}[job.action]||'Проверка'} · сервисов: ${job.targets?.length||0}${p.workers?' · воркеров: '+p.workers:''}${p.phase==='error'?' · подробности в журнале':''}`:'Настройте сервисы и запустите поиск.';$('log').textContent=value.log||'Здесь появится ход проверки.';const exp=value.export||{};$('nav-count').textContent=fmt(p.passed??exp.passed??0);$('live-passed').textContent=fmt(p.passed??exp.passed??0);if(exp.profile)$('export-note').textContent=`Готовый экспорт: ${fmt(exp.exported)} из ${fmt(exp.passed)} подходящих · проверено ${fmt(exp.checked)} / ${fmt(exp.candidates)} · ${exp.sort==='speed'?'по скорости':'по качеству'} · ${exp.generated_at?new Date(exp.generated_at*1000).toLocaleString('ru-RU'):'последний экспорт'}. Изменили фильтры? Нажмите «Сформировать экспорт».`;document.querySelectorAll('[data-download]').forEach(n=>n.disabled=!(value.downloads||[]).includes(n.dataset.download)||(value.running&&p.phase==='exporting'));const report=p.sources?p:value.sources||{};renderSources(report,value.source_urls||[]);const finished=job.id&&!value.running?job.id:null;if(finished&&finished!==lastFinished){lastFinished=finished;if(job.action!=='collect')loadResults();}}
function renderSources(report,urls){const sourceRows=report.sources||[];$('sources-status').textContent=sourceRows.length?`${sourceRows.filter(r=>r.complete).length} / ${sourceRows.length} загружены полностью`:'Загрузки ещё не было';$('source-rows').innerHTML=sourceRows.length?sourceRows.map(r=>{let label=r.source?urls[r.source-1]||'Источник '+r.source:'Свой список';return `<tr><td title="${esc(label)}" style="max-width:440px;overflow:hidden;text-overflow:ellipsis">${esc(label)}</td><td>${fmt(r.rows)}</td><td>${fmt(r.invalid)}</td><td class="${r.complete?'':'status-error'}">${r.complete?(r.rows===0?'Пустой список':r.rows===r.invalid?'Нет подходящих адресов':'Готово'):esc(r.error||'Не завершено')}</td></tr>`;}).join(''):'<tr><td colspan="4" class="empty">Здесь будут результаты последнего сбора.</td></tr>';}
async function poll(){if(polling)return;polling=true;try{renderState(await api('/api/state'));}catch(e){$('phase').textContent='Нет связи с приложением';}finally{polling=false;}}
async function loadResults(){if(resultBusy)return;resultBusy=true;$('refresh-results').disabled=true;try{const q=new URLSearchParams({sort:$('result-sort').value,min_success:$('result-min').value,offset});const data=await api('/api/results?'+q);rows=data.rows;resultTargets=data.targets;resultTotal=data.total;$('result-context').textContent=data.profile?`Проверено для: ${data.targets.map(t=>t.name?`${t.name} (${t.url})`:t.url).join(' + ')} · должны работать все сервисы`:'После проверки здесь появятся подходящие адреса.';$('result-total').textContent=fmt(data.total)+' подходящих';$('page-number').textContent=`${Math.floor(offset/50)+1} / ${Math.max(1,Math.ceil(data.total/50))}`;$('prev').disabled=offset===0;$('next').disabled=offset+50>=data.total;$('result-rows').innerHTML=rows.length?rows.map((r,i)=>`<tr><td>${fmt(offset+i+1)}</td><td>${esc(r.proxy)}</td><td><span class="score">${r.score.toFixed(1)}</span></td><td>${Number(r.latency_ms).toFixed(0)} мс</td><td>${Number(r.jitter_ms).toFixed(0)} мс</td><td>${(r.min_target_reliability*100).toFixed(0)}%</td><td><button class="text-link" data-details="${i}">Детали ↗</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">По этим условиям пока нет подходящих прокси. Проверьте прогресс, URL сервисов и порог успешности.</td></tr>';$('result-rows').querySelectorAll('[data-details]').forEach(n=>n.onclick=()=>details(rows[Number(n.dataset.details)]));}catch(e){toast(e.message,true);}finally{resultBusy=false;$('refresh-results').disabled=false;}}
function details(row){$('details-title').textContent=row.proxy;const body=$('details-body');body.innerHTML=resultTargets.map((t,i)=>`<h3>${esc(t.name||'Сервис '+(i+1))} · ${esc(t.url)}</h3><div class="table-wrap"><table><thead><tr><th>Попытка</th><th>Ответ</th><th>Время</th><th>Байт</th><th>Результат</th></tr></thead><tbody>${row.samples.filter(s=>s.target===i).map(s=>`<tr><td>${s.attempt}</td><td>${s.status??'—'}</td><td>${s.ms} мс</td><td>${fmt(s.bytes)}</td><td class="${s.ok?'':'status-error'}">${s.ok?'Успешно':esc(s.error)}</td></tr>`).join('')}</tbody></table></div>`).join('');$('details-dialog').showModal();}
$('close-details').onclick=()=>$('details-dialog').close();
$('add-target').onclick=()=>addTarget();$('save-settings').onclick=save;$('save-sources').onclick=save;
$('start').onclick=()=>start('run');$('resume').onclick=()=>start('scan');$('recheck').onclick=()=>start('recheck');$('collect').onclick=()=>start('collect');$('export').onclick=()=>start('export');
$('stop').onclick=async()=>{try{$('stop').disabled=true;await api('/api/stop',{});toast('Останавливаем и сохраняем завершённые проверки.');await poll();}catch(e){toast(e.message,true);}};
$('refresh-results').onclick=()=>{offset=0;loadResults();};['result-sort','result-min'].forEach(id=>$(id).onchange=()=>{offset=0;loadResults();});$('prev').onclick=()=>{offset=Math.max(0,offset-50);loadResults();};$('next').onclick=()=>{offset+=50;loadResults();};
$('sources').oninput=updateSourceCount;$('use_sources').onchange=updateSourceCount;
$('reset-sources').onclick=async()=>{try{const value=await api('/api/defaults');$('sources').value=value.sources.join('\n');updateSourceCount();toast('Встроенные источники восстановлены. Сохраните настройки.');}catch(e){toast(e.message,true);}};
$('import-file').onchange=async event=>{const file=event.target.files[0];if(!file)return;if(file.size>20_000_000){toast('Максимум 20 МБ на файл.',true);return;}$('proxies').value=await file.text();toast('Список загружен. Он будет добавлен при сборе.');};
document.querySelectorAll('[data-download]').forEach(node=>node.onclick=async()=>{try{node.disabled=true;const response=await fetch('/api/download/'+node.dataset.download,{headers:{'X-Workbench-Token':token}});if(!response.ok)throw new Error('Файл ещё не готов.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=node.dataset.download;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){toast(e.message,true);}finally{node.disabled=false;}});
(async()=>{try{fill(await api('/api/settings'));await poll();setInterval(poll,2000);}catch(e){toast(e.message,true);}})();

function renderTheme(){const dark=document.documentElement.dataset.theme==='dark';$('theme-toggle').textContent=dark?'☀ Светлая тема':'☾ Тёмная тема';$('theme-toggle').setAttribute('aria-label',dark?'Включить светлую тему':'Включить тёмную тему');}
$('theme-toggle').onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('proxy-workbench-theme',theme);}catch{}renderTheme();};renderTheme();
